"""
ppt_generator.py
Converts the agent's SLIDE-formatted text into a real, downloadable .pptx file.
"""

import re
import io
from pptx import Presentation
from pptx.util import Inches, Pt


def parse_slides(content: str):
    """
    Parses text like:

    SLIDE 1: Title here
    - bullet
    - bullet

    SLIDE 2: Next title
    - bullet

    into a list of dicts: [{"title": ..., "bullets": [...]}, ...]
    """
    slide_blocks = re.split(r"SLIDE\s+\d+:\s*", content)
    slides = []
    for block in slide_blocks:
        block = block.strip()
        if not block:
            continue
        lines = block.split("\n")
        title = lines[0].strip()
        bullets = []
        for line in lines[1:]:
            line = line.strip()
            if line.startswith("-") or line.startswith("•"):
                bullets.append(line.lstrip("-•").strip())
            elif line:
                bullets.append(line)
        slides.append({"title": title, "bullets": bullets})
    return slides


def build_pptx(topic: str, content: str) -> io.BytesIO:
    """
    Builds a .pptx file in memory from parsed slide content and returns
    a BytesIO buffer ready for Streamlit's download_button.
    """
    slides_data = parse_slides(content)

    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    bullet_slide_layout = prs.slide_layouts[1]

    # Title slide
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = topic
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by EngiTutor AI Agent"

    # Content slides
    for s in slides_data:
        slide = prs.slides.add_slide(bullet_slide_layout)
        slide.shapes.title.text = s["title"]
        body = slide.placeholders[1].text_frame
        body.clear()
        if s["bullets"]:
            body.text = s["bullets"][0]
            for bullet in s["bullets"][1:]:
                p = body.add_paragraph()
                p.text = bullet
                p.level = 0
        else:
            body.text = ""

    buffer = io.BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer
